# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

```yaml
trigger:
  branches: 
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm test
  displayName: 'npm install and test'
- task: Docker@2
  inputs:
    containerRegistry: 'My Docker Hub'
    repository: 'my-app'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build Docker image'
- task: Docker@2
  inputs:
    containerRegistry: 'My Docker Hub'
    repository: 'my-app'
    command: 'push'
  displayName: 'Push Docker image'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'My Azure Subscription'
    azureResourceGroup: 'My Resource Group'
    kubernetesServiceEndpoint: 'My Kubernetes Service Connection'
    namespace: 'my-namespace'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'config.yml'
  displayName: 'Deploy to Kubernetes'
```
